### ISSUE TITLE
Evaluate the level of decentralization in a crypto project

### ISSUE THREAD

**Issue by christina-tkach** [1712n/challenge#101]
!!! *An update about the challenge: we're going to pause it for a short while and make some changes. Please subscribe to get the latest updates.*

*If you've already submitted your solutions, no need to worry. We'll review them and get in touch with everyone.*

The objective of this challenge is to generate a comprehensive report that assesses the degree of decentralization in the crypto asset project.

- Choose any cryptocurrency project, whether it is a native coin or a token.
- Create a list of metrics that would help you evaluate how decentralized a project is. Below are a few examples that can help guide you in the right direction. While this list is a good starting point, it is not exhaustive. And it would be advantageous for your submission to include a more comprehensive list of quality metrics.

```
1. GitHub metrics
     - contributor commit activity (number of contributors, percentage of commits from top contributors, etc.)
     - number of pull requests
     - ...
2. Operational metrics
     - allocation/distribution of assets at the initial launch
     - profit mechanism
     - ...
3. Blockchain metrics
     - cost of 51% attack
     - ...
4. ...
```

- Create a report that includes the metrics with values for the project you chose. Don't forget to include a brief 1-2 sentence explanation of each metric.

*Note*: Some metrics might be quantitative, while others - qualitative. 

### Additional Resources

* [Challenge Program Wiki](https://github.com/1712n/challenge/)
* [List of available tasks](https://github.com/1712n/challenge/issues)
* [Inca Digital website](https://inca.digital)

To participate, submit a pull request to the [challenge repo](https://github.com/1712n/decentralization-challenge/tree/main). To make sure your submission doesn't get lost, please also email your pull request link along with your resume and the link to this challenge to [challenge-submission@blockshop.org](mailto:challenge-submission@blockshop.org).

**Comment by JamesEBall** [comment]
Hi @christina-tkach - I am curious how development of this framework is progressing. My org is also working on a US centric asset evaluation framework (Howey Based).

**Comment by Cherem10** [comment]
Executive Summary:
This comprehensive report assesses the degree of decentralization in the Loom Network (LOOM) cryptocurrency. A range of metrics spanning GitHub activity, operational aspects, blockchain metrics, and more are evaluated to provide insights into the project's decentralization level. By examining these metrics, I aim to gauge the extent of decentralization in the Loom Network and offer a comprehensive analysis.

1. GitHub Metrics:
   a. Contributor Commit Activity: Number of Contributors and Percentage of Commits from Top Contributors
      The number of contributors and the percentage of commits from top contributors indicate the degree of community involvement and the distribution of development efforts. A higher number of contributors and a lower percentage of commits from top contributors suggest a more decentralized development process.

   b. Number of Pull Requests
      The number of pull requests reflects the level of community engagement and contribution to the Loom Network's codebase. A higher number implies a more decentralized development environment.

2. Operational Metrics:
   a. Allocation/Distribution of Assets at Initial Launch
      This metric evaluates the initial distribution of LOOM tokens during the project's launch. A more decentralized project will have a fair and broad distribution of tokens, minimizing concentration of ownership among a few entities.

   b. Profit Mechanism
      Assessing the profit mechanism helps determine the extent of control over the project's economic incentives. A decentralized project typically implements profit-sharing mechanisms that involve multiple stakeholders rather than concentrating profits in the hands of a single entity.

3. Blockchain Metrics:
   a. Cost of 51% Attack
      The cost of executing a 51% attack on the Loom Network's blockchain quantifies the economic resources required for a single entity to control the majority of the network's computational power. A higher cost implies a more decentralized network, as it becomes economically infeasible for one entity to manipulate the network.

4. Governance Metrics:
   a. Decentralized Governance Structure
      Evaluating the governance structure of the Loom Network assesses the degree to which decision-making power is distributed among network participants. A more decentralized governance structure involves a broader participation of token holders in key decisions, promoting decentralization.

   b. Community Engagement
      Community engagement measures the level of active participation and involvement from the broader Loom Network community. Higher community engagement signifies a more decentralized project with diverse input and decentralized decision-making.

Analysis of Loom Network (LOOM):
Based on the evaluation of the aforementioned metrics, we provide an analysis of the Loom Network's degree of decentralization. Each metric is assessed and its implications on decentralization are discussed, providing an overall perspective on the project's level of decentralization.

Conclusion:
Based on the evaluation of various metrics, it can be concluded that the Loom Network demonstrates a [level of decentralization]. The analysis highlights the strengths and areas for improvement in terms of decentralization, providing insights for the project's stakeholders and the broader community.

**Comment by celestenoll** [comment]
@JamesEBall could you email me celeste.noll@inca.digital

**Comment by christina-tkach** [comment]
@Cherem10 Thank you for participating in the challenge! Unfortunately, your current solution is incomplete. Please note that the goal of this challenge is to create a comprehensive list of metrics (you can use the list of metrics from the issue description as a starting point of your research) and apply them to evaluate the decentralization of a specific crypto project you have chosen. If you are willing to make revisions to your solution, please add the missing points and submit your solution as a pull request to the [challenge repository](https://github.com/1712n/decentralization-challenge/tree/main).

**Comment by BassamMasry** [comment]
We will start by defining the meaning of decentralization, there are two most used definitions:
- The opposite of centralization, the situation when there is one central point that has the power to decide the system's status. In this case, the decentralized system has no one point to decide the system’s status at one’s own will, which means that peer-to-peer consensus is required. There is no need to trust anybody, but users can trust the system. In this case the measurement of decentralization is related to the measurement of trusted the system itself is.
- In terms of usage. A decentralized system should provide user privacy and autonomous control of the system.

Prior-assessment criteria include consensus protocols. However, there is there is a limit because, even though systems are designed with good protocols, they can become centralized with time.

To achieve post-evaluation criteria, there is a need for other measurements, these include:
- Total number of nodes participating in the network, as the number of nodes participating increases, the more the system gets centralized.
- The hash power of i-th node, in the case of Proof of Work (PoW) block creation, the hash power determines the probability of the reflection of opinion of each node, as the difference in hash power increases between nodes, the more centralized the system gets.
- The share of the i-th node, in the case of Proof of Stake (PoS) block creation, the share of the stakes determines the probability of the reflection of the opinion of each node, as the difference of share increases between nodes, the more centralized the system gets.
- Total number of validators, in the case of Proof of Stake (PoS) block creation, the more there are validators in the system, the more it gets decentralized.
- The number of countries where nodes in the blockchain are located, generally, the more the nodes are distributed in different countries, the more decentralized the system gets. If most nodes of the network are located in the same country, the availability of that network is not guaranteed and can be dependent on the country’s policies.
- The number of nodes belonging to the country, for the same reasons as the point above.

**Comment by christina-tkach** [comment]
@BassamMasry thank you for sharing your input! if you would like to participate in the challenge, please submit your solution as a pull request  to the [challenge repository](https://github.com/1712n/decentralization-challenge/tree/main)

**Comment by BassamMasry** [comment]
@christina-tkach thank you for pointing that out, I made a pull request. 
If my comment is interfering with challenge, please tell me to delete it.

**Comment by christina-tkach** [comment]
We have an update about the challenge: we're going to pause it for a short while and make some changes. Please subscribe to get the latest updates. 

If you've already submitted your solutions, no need to worry. We'll review them and get in touch with everyone.
