### ISSUE TITLE
P2P markets report summary

### ISSUE THREAD

**Issue by evgenydmitriev** [1712n/challenge#59]
Take 2 countries from the list below and write a comparative report summary on the p2p payment-based local markets. Feel free to add comparative graphs and tables to illustrate your points:

- Afghanistan
- Chile
- Croatia
- Dominican Republic
- El Salvador
- Ecuador
- Iran
- Kazakhstan
- Morocco
- Pakistan
- Peru
- Philippines
- Saudi Arabia
- Switzerland
- Ukraine
- United Arab Emirates
- Vietnam

### Additional Resources

* [Challenge Program Wiki](https://github.com/1712n/challenge/)
* [List of available tasks](https://github.com/1712n/challenge/issues)
* [Inca Digital website](https://inca.digital)

Please email challenge-submission@blockshop.org with your solution, and don't forget to include a link to this issue and attach your resume. Don't hesitate to ask us questions by commenting in this issue or emailing us at challenge-program@blockshop.org

**Comment by smahapa3** [comment]
**Philippines** 

Peer-to-Peer (P2P) Lending or what others commonly now as online loans have been in the Philippines for about four years now. Since its inception in the country, this type of financial platform remains to be constant in terms of helping people get a hold of their urgent monetary needs. There is a big potential for alternative lending in the Philippines and plans to continue attracting investments for this market are growing. 

For instance, Blend.PH prides itself as one of the P2P pioneers in the Philippines. With minimum investments for as low as $96 (PHP5,000) and interest rates ranging from 8-30%, Blend PH has lured lenders including millennials, housewives, overseas Filipino workers (OFWs) and even institutional investors. 

Additionally, ROBO.CASH investors have backed €2.4m (£2m) of loans in the Philippines in the first three months since the peer-to-peer lender launched a partnership in the country.

The Latvia-based P2P platform began providing short-term loans in the Philippines in December 2018 and the market now represents the highest volume of lending so far this year. The platform said it doubled its investor base in 2018, with its loanbook hitting €5m, as it expanded its product range and scaled up its lending during the year.

While Kiva has been beneficial to provide support to under-developed communities in the Philippines, and has funded approximately USD 1.55 billion in loans, FundKo and GoodKredit have also been beneficial and important P2P platforms to connect crowds of lender investors who are ready to fund qualified borrowers at lower rates and flexible terms, to offer monthly payments. Its loan products are personal, maternity, cashback, business, and working student loans.

However, COVID 19 destroyed many small businesses and investors pulled out of P2P platform. In order to to fast-track growth and stimulate a recovery, Acudeen is another company which is using a P2P platform -- with a lending license-- to re-enter the P2P business and make loans within a fast-moving consumer goods vertical. 

For a company of that size, there is plenty of scope to scale, both within the conglomerate and the broader Philippines market, which Kumar says is as large as $40 billion for all P2P and invoice financing, claims the owner. 


**Ukraine** 

Project simzirok.com was created in 2013 with the purpose to enable individuals to freely invest their funds in profitable projects to obtain additional profits from loans granted. Similarly, for borrowers who seek to borrow money and do not want to apply to a bank, it is an opportunity to find funds for their purpose (purchase of equipment, payment for training, starting own business, family rest, payment for medical care, etc.) with lower interest rates, than banks offer today.

PrivatBank, a leading Ukrainian bank, launched an advanced P2P and P2B lending service, allowing individuals and businesses to borrow money from each other directly. The service has been made available both online and via the bank’s physical outlets. Thus small businesses may request amounts of up to Hr 300,000 ($11,000). Credit requests are submitted to potential lenders during up to two months.

MoCash is yet another Ukrainian p2p lending platform that brings together private borrowers and investors. Using MoCash, people may raise up to UAH 500,000 in business loans directly from other individuals. Unlike banks, thier platform raises funds for borrowers without any collateral and, compared to MoCash, banks charge higher commission fees as well as most banks an annuity system, which makes the effective interest on loan much higher than the declared one, rendering them a second alternative to the preferred MoCash platform for a target demographic of IT professionals mostly, as well as owners of medium-sized enterprises.

Overall, the dynamics and structure of peer-to-peer lending in various countries for the period 2005-2016 led to the conclusion that in Ukraine, there is a decline in the share of bank lending in
favor of peer-to-peer lending in the total amount of loans with an increasing role of non-bank and hybrid forms of lending in ensuring economic growth. 



**Conclusion** 

As the internet grows, we are seeing a greater push towards decentralization and diversification with the help of cryptography and blockchain development. P2P platforms which have been built thus far are proving to be a great alternative creation which have allowed small investors to make gains and many communities who were earlier unable to access the market now able to become important game-players in the ever-changing face of the money lending world.  
P2P platforms like Venmo and Ziina have made personal payments hassle-free and as easy as sending a text message. Finance should be accessible to all, with P2P, crypto, and DeFi, the financial system of the world is set on the path of revolutionary transformation allowing everyday people to find alternative, cheaper, and more accessible ways to control their own assets and preserve their wealth how they deem fit.





Sources: 
https://www.p2pfinancenews.co.uk/2019/03/25/philippines-becomes-biggest-p2p-lending-market-for-robo-cash/ 
https://www.digfingroup.com/p2p-platform/
https://fintechnews.sg/19702/lending/p2p-lending-in-philippines-rising/
https://asianbankingandfinance.net/financial-technology/exclusive/p2p-lender-blend-ph-targets-nearly-20m-portfolio-2021-in-financial-in
https://www.moneymax.ph/loans/articles/peer-to-peer-lending-philippines
https://lawstrust.com/en/news/mikrokreditovanie-i-r2r-kreditovanie
https://inventure.com.ua/en/news/ukraine/privatbank-launches-peer-to-peer-lending
https://ain.ua/special/usaid-mocash-eng/

**Comment by smahapa3** [comment]
**Philippines** 

Peer-to-Peer (P2P) Lending or what others commonly now as online loans have been in the Philippines for about four years now. Since its inception in the country, this type of financial platform remains to be constant in terms of helping people get a hold of their urgent monetary needs. There is a big potential for alternative lending in the Philippines and plans to continue attracting investments for this market are growing. 

For instance, Blend.PH prides itself as one of the P2P pioneers in the Philippines. With minimum investments for as low as $96 (PHP5,000) and interest rates ranging from 8-30%, Blend PH has lured lenders including millennials, housewives, overseas Filipino workers (OFWs) and even institutional investors. 

Additionally, ROBO.CASH investors have backed €2.4m (£2m) of loans in the Philippines in the first three months since the peer-to-peer lender launched a partnership in the country. The Latvia-based P2P platform began providing short-term loans in the Philippines in December 2018 and the market now represents the highest volume of lending so far this year. The platform said it doubled its investor base in 2018, with its loanbook hitting €5m, as it expanded its product range and scaled up its lending during the year.

While Kiva has been beneficial to provide support to under-developed communities in the Philippines, and has funded approximately USD 1.55 billion in loans, FundKo and GoodKredit have also been beneficial and important P2P platforms to connect crowds of lender investors who are ready to fund qualified borrowers at lower rates and flexible terms, to offer monthly payments. Its loan products are personal, maternity, cashback, business, and working student loans.

However, COVID 19 destroyed many small businesses and investors pulled out of P2P platform. In order to to fast-track growth and stimulate a recovery, Acudeen is another company which is using a P2P platform -- with a lending license-- to re-enter the P2P business and make loans within a fast-moving consumer goods vertical. For a company of that size, there is plenty of scope to scale, both within the conglomerate and the broader Philippines market, which Kumar says is as large as $40 billion for all P2P and invoice financing, claims the owner. 


**Ukraine** 






**Conclusion** 







Sources: 
https://www.p2pfinancenews.co.uk/2019/03/25/philippines-becomes-biggest-p2p-lending-market-for-robo-cash/ 
https://www.digfingroup.com/p2p-platform/
https://fintechnews.sg/19702/lending/p2p-lending-in-philippines-rising/
https://asianbankingandfinance.net/financial-technology/exclusive/p2p-lender-blend-ph-targets-nearly-20m-portfolio-2021-in-financial-in
https://www.moneymax.ph/loans/articles/peer-to-peer-lending-philippines

**Comment by GraysonAlto** [comment]
**P2P Markets in Vietnam and Saudi Arabia** 
The infrastructure of a peer-to-peer network allows two or more computer systems to exchange information and resources in an efficient way over long distances, cost effectively, and with more reliability. The main forms of P2P markets in the growing space are Lending and Payment services.

**Vietnam**
P2P Lending:
Following heavy regulation on P2P lending from the Peoples Bank of China in 2016, the number of P2P lending services dwindled from 2,680 in 2016, to 343 in 2019; subsequently many of these firms shifted to a growing market in nearby Vietnam. With P2P infrastructures rapidly emerging, the service is neither prohibited nor entirely legal as the government hasn’t implemented a framework on how to handle bankless transactions. Today there are currently 100+ lending companies working within Vietnam. Currently 60% of Vietnamese small-medium companies are not qualified to receive a loan due to lack of assets and capital, P2P lending profoundly increases the number of businesses that can access a loan with annual interest rates ranging from 9-10%. 
<img width="229" alt="image" src="https://user-images.githubusercontent.com/35880746/141540900-b4f9fcc4-c5b3-413d-9ae9-b347eec60d2c.png"> 
P2P Payments:            
The main form of P2P payments in Vietnam is an established and rapidly growing cryptocurrency market. Vietnam is second in the world in adoption rates at 5.9%. Surveys published even show that 41% of respondents had claimed they have bought cryptocurrency in Vietnam. There are discrepancies in how big the market is, but examples such as Vietnamese based game “Axie Infinity”s token reaching a market cap of nine-billion at the time of writing show that Vietnam is here to stay as a global blockchain leader. In February of 2021, Visa and remittance platform MoneyGram, partnered to form the country's first P2P payment system working with Vietnamese banks across the country. The new service allows remittance to be received from the U.S, UK, 18 other European countries through the MoneyGram mobile app. Vietnam is a top 10 remittance receiver in the world with 15.7 billion coming into the country in 2020. 

**Saudi Arabia**        <img width="219" alt="image" src="https://user-images.githubusercontent.com/35880746/141541001-02baf151-9e52-44e6-9c6d-ed4b734fe897.png">

P2P Lending:
Subsequently after the 2014 oil price crash, Saudi Arabia released the “Vision 2030” in which the government is pushing for diversified business away from oil and into a booming private economic sector. Saudi start up investments have risen from raising $8m in 2016, to over $150m in 2020. P2P lending is the catalyst for a booming private sector accounting for almost 20% of all startup investments. In 2020 there were 12 P2P lenders operating in Saudi Arabia. In February 2021, P2P lending platforms titled Raqamyah, and Lendo respectfully raised $2.3m and $7.2m in Series A fundraising. 

P2P Payments:
In addition to economic diversification, Saudi Arabia hopes to reach a cashless society as part of the “Vision 2030.” In April 2021, the Saudi Arabian Monetary Authority (SAMA) teamed up with Mastercard company to release Vocalink with the aim of upgrading the country’s payment infrastructure and boosting the digital economy with a state backed P2P payment system. In addition to Vocalink, P2P blockchain payments in the form of cryptocurrencies are legal. Saudi Arabia has only one bitcoin atm which corresponds with the fact that only 1.3% of the country has adopted cryptocurrencies compared to a 3.9% global average. This number is expected to grow with a growing financial technology industry and a 94% internet usage rate amongst its citizens. 

**Summary**

As P2P lending and blockchain payments continue to advance, more integration of the two will develop. Compound Finance for example is a lending platform where lenders can deposit Ethereum derivatives into a large pool, and borrowers with no background check can borrow up to the amount they use as collateral. Compound Finance also acts as a Decentralized Autonomous Organization (DAO), whereby holder of the Compound token (COMP) participate in the governance system by submitting and voting on any proposals to make changes to the Compound blockchain system. The COMP token also acts as a P2P payment system between wallet owners, blurring the lines between the separation of lending and payments. Lending and Payments are heading into a P2P direction, largely in part to the fact that anyone with access to the internet across the world is entitled to the financial and banking tools they deserve. 

               
Works Cited

https://vir.com.vn/proper-rules-for-p2p-lending-in-demand-82299.html 

https://www.remitfinder.com/blog/top-10-countries-with-highest-received-remittances-during-covid-19-pandemic 

https://news.bitcoin.com/finders-poll-shows-vietnam-holds-the-highest-percentage-of-crypto-ownership-worldwide/ 

https://www.sofi.com/learn/content/what-is-compound-finance-in-defi/ 

https://web.derayah.com/wp-content/uploads/2017/12/concept_study_p2p_lending_17.pdf

https://www.p2pfinancenews.co.uk/2021/07/20/is-saudi-arabia-set-to-become-the-next-p2p-hub/

https://www.linkedin.com/pulse/lending-saudi-ripe-disruption-p2p-platforms-like-lead-alrajhi-mba

https://fintechos.com/blogpost/fintech-focus-trends-and-big-ideas-in-the-middle-east/ 

https://www.cekindo.vn/blog/reasons-peer-to-peer-lending-hot-vietnam 

https://hanoitimes.vn/legal-framework-necessary-to-avoid-collapse-of-p2p-lending-in-vietnam-315384.html

https://www.researchgate.net/publication/338082048_Peer-to-peer_lending_in_Vietnam_and_experience_from_other_countries

https://kr-asia.com/reviving-trust-p2p-lending-in-vietnam

https://ibsintelligence.com/ibsi-news/moneygram-launches-p2p-payment-solution-in-vietnam-using-visa-direct/

https://www.americanbanker.com/payments/news/saudi-arabias-instant-payments-service-goes-live 

https://www.fintechfutures.com/2019/04/first-real-time-payments-launched-in-saudi-arabia/

**Comment by akouirouk** [comment]
Attached below is my report:

[P2P Markets Report Summary - Alexandros Kouiroukidis.docx](https://github.com/inca-digital/challenge/files/7573865/P2P.Markets.Report.Summary.-.Alexandros.Kouiroukidis.docx)

**Comment by apDacey** [comment]
# P2P Markets Report Summary
**In this report I compare the P2P markets of Iran and Vietnam**
[Angelo Dacey - P2P Markets Report.docx](https://github.com/inca-digital/challenge/files/7794979/Angelo.Dacey.-.P2P.Markets.Report.docx)

**Comment by m1chael-lu** [comment]
I've attached my report below:

[Afghanistan and Ukraine P2P Market Comparison.docx](https://github.com/inca-digital/challenge/files/7797197/Afghanistan.and.Ukraine.P2P.Market.Comparison.docx)

**Comment by AWil-WilA** [comment]
I've attached my report for Vietnam and Morocco P2P Report
[P2P Report.docx](https://github.com/inca-digital/challenge/files/8758505/P2P.Report.docx)

**Comment by evgenydmitriev** [comment]
@akouirouk successfully completed the challenge and was hired by [Inca Digital](https://inca.digital/)! Congrats 🎉

The challenge is still open!

**Comment by antonasam** [comment]
My report for Ukraine and Iran is attached below.
[Inca_Challenge#59.pdf](https://github.com/1712n/challenge/files/10698510/Inca_Challenge.59.pdf)
