### ISSUE TITLE
Remittances KYC report summary

### ISSUE THREAD

**Issue by evgenydmitriev** [1712n/challenge#60]
Write a report summary on KYC requirements for the top 3 remittance providers that leverage blockchain technologies in one of the following countries:

- Afghanistan
- Chile
- Croatia
- Dominican Republic
- El Salvador
- Ecuador
- Iran
- Kazakhstan
- Morocco
- Pakistan
- Peru
- Philippines
- Saudi Arabia
- Switzerland
- Ukraine
- United Arab Emirates
- Vietnam

### Additional Resources

* [Challenge Program Wiki](https://github.com/1712n/challenge/)
* [List of available tasks](https://github.com/1712n/challenge/issues)
* [Inca Digital website](https://inca.digital)

Please email challenge-submission@blockshop.org with your solution, and don't forget to include a link to this issue and attach your resume. Don't hesitate to ask us questions by commenting in this issue or emailing us at challenge-program@blockshop.org

🎉  @akouirouk successfully solved the challenge and was hired by Inca Digital.

**Comment by akouirouk** [comment]
Attached below is my report summary.

[Remittances KYC Report Summary - Alexandros Kouiroukidis.docx](https://github.com/inca-digital/challenge/files/7551668/Remittances.KYC.Report.Summary.-.Alexandros.Kouiroukidis.docx)

**Comment by ryan-guy-i** [comment]
My report is attached.
[KYC Remittance Philippines.docx](https://github.com/inca-digital/challenge/files/7645715/KYC.Remittance.Philippines.docx)

**Comment by Zan-XX** [comment]
Here is my report summary:

[KYC Requirements of UAE Exchange, Ripple, and LuLu Exchange (1).pdf](https://github.com/inca-digital/challenge/files/7797259/KYC.Requirements.of.UAE.Exchange.Ripple.and.LuLu.Exchange.1.pdf)

**Comment by Zan-XX** [comment]
Here is my report summary:
[KYC Requirements of UAE Exchange, Bank Alfalah, and LuLu Exchange.pdf](https://github.com/inca-digital/challenge/files/7797261/KYC.Requirements.of.UAE.Exchange.Bank.Alfalah.and.LuLu.Exchange.pdf)

**Comment by bwogisean** [comment]
Attached below is is my report.
[KYCrequirementsRemittanceProviders.pdf](https://github.com/inca-digital/challenge/files/7991775/KYCrequirementsRemittanceProviders.pdf)

**Comment by jayyluck** [comment]
Introduction
The fight against financial fraud and money laundering relies heavily on KYC, with client identification acting as the most vital element since it is the initial step in boosting performance in future phases of the process. Financial institutions around the world face huge risks because of the global counter-terrorism and anti-money laundering settings. KYC is an abbreviation for Know Your Customer, which can also be spelled Know Your Client. If you are opening a new account, you must complete a Know Your Customer check. This process is repeated frequently throughout time to identify and verify the client's identity. Banks must verify the identity of their customers before granting them loans. Banks may refuse to create a bank account or cancel a business relationship if a client does not meet the minimal KYC requirements.
A blockchain is a digital log of transactions that is replicated and shared across the whole computer network on the blockchain (Yaga et al., 2019). All participants' ledgers are automatically updated when a new transaction takes place on the blockchain, and each block contains a sequence of transactions. Distributed Ledger System, or DLT, is a technology that allows several parties to manage a single database.
Bank Descriptions
SEBA bank
SEBA is the owner and operator of a crypto trading banking platform that is intended to serve as a link between traditional and digital assets. A variety of services provided by the company enable customers to store, trade, and control cryptocurrencies, digital assets, and traditional securities all in one location, providing customers and clients with easy-to-use, open investment solutions for their crypto and standard assets.
Sygnum bank
Sygnum bank is a Provider of cryptocurrency financial services with the goal of increasing transparency in the digital currency market. Corporates, banks, and other financial companies are able to invest in the digital asset market with total confidence because of the company's institutional-grade custody, fiat-digital asset gateway, brokerage, and b2b banking services provided by Lombard.
Zurich Cantonal Bank
Switzerland's fourth-biggest bank, Zurich Cantonal Bank, has assets of more than CHF 150 billion, making it both the leading cantonal bank and the main largest bank in the Greater Zurich area. Switzerland's Canton of Zurich owns a majority stake in ZKB as an autonomous, incorporated public law institution. The Cantonal Council of Zurich is in charge of overall oversight of ZKB, as outlined in the Cantonal Bank Act of Zurich. If ZKB's resources are insufficient, the canton of Zurich is legally responsible for all of the bank's liabilities. In periods of economic instability, this cantonal guarantee functions as a stabilizing element for the financial market.
KYC requirements
Banks' KYC procedures comprise all necessary steps to verify the legitimacy of their customers and to assess and monitor risks. Onboarding procedures help to prevent and identify terrorism financing as well as other criminal corruption schemes. The KYC method now includes paperwork such as utility bills as proof of address and biometric verification in addition to face and ID card verification. Anti-money laundering and Know Your Customer standards must be adhered to by banks in order to prevent fraud. Compliance with Know Your Customer (KYC) standards is the responsibility of the banks.
According to Switzerland laws, the following are the KYC requirement for the above banks:
To Onboard Domestic Person
Nationality and identity documents
To Onboard International Individual
Photograph, Driving License, Identity Card, Address, Date of Birth, Identity Documents, Passport, Name, and Nationality
Corporate Requirements
Commercial Register and Registered Office in Switzerland
 
 
 
 
 
Reference
Yaga, D., Mell, P., Roby, N., & Scarfone, K. (2019). Blockchain technology overview. arXiv preprint arXiv:1906.11078.

**Comment by evgenydmitriev** [comment]
@akouirouk successfully completed the challenge and was hired by [Inca Digital](https://inca.digital/)! Congrats 🎉

The challenge is still open!

**Comment by apDacey** [comment]
My report summary is attached below.

[Angelo Dacey - KYCReportSwitzerland.docx](https://github.com/1712n/challenge/files/9649876/Angelo.Dacey.-.KYCReportSwitzerland.docx)

**Comment by Zhan-Ar** [comment]
Here is my report on KYC requirements - Kazakhstan.

[KYC requirements Kazakhstan.docx](https://github.com/1712n/challenge/files/9759893/KYC.requirements.Kazakhstan.docx)
